# Generated by Django 3.2 on 2021-04-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20210429_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='direction',
            field=models.IntegerField(null=True),
        ),
    ]
