# Generated by Django 3.1.4 on 2021-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20210501_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='id_station',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
