# Generated by Django 3.1.4 on 2021-05-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20210504_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='id_station',
        ),
    ]
