# Generated by Django 3.2 on 2021-04-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='lines',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='station_ids',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
